name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3

      # check to ensure all JSON files are valid in the repository
      - name: json syntax check
        uses: limitusus/json-syntax-check@94555527ace7b96df4a600874a4aafd735842780 # pin@v2.0.0
        with:
          pattern: "\\.json$"

      - name: Cache node modules
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # pin@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Get files needed
        run: npm run prebuild
        env:
          GITHUB_TOKEN: ${{ secrets.HIDEOUT_BOT_TOKEN }}

      - name: Test
        run: npm run test
