name: Combine PRs

on:
  schedule:
    - cron: "0 1 * * 3" # Wednesday at 01:00
  workflow_dispatch:

jobs:
  combine-prs:
    uses: the-hideout/reusable-workflows/.github/workflows/combine-prs.yml@main
    secrets: inherit
